import Head from "next/head";
import { Inter } from "@next/font/google";
import Tabs from "../../components/Tabs";
import Content from "../../components/Content";
import NavigationPoint from "../../components/NavigationPoint";
import NewsFeed from "../../components/NewsFeed";
import { CardContainer } from "../../utils";
import { useAuth } from "../../context/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export default function JobBoard() {
  const { user } = useAuth();
  return (
    <>
      <Head>
        <title>LetChat | Job Board</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main> */}
      <Content
        title={"Job Board"}
        navigation={<NavigationPoint />}
        newsfeed={<NewsFeed title={"News Feed"} />}
        central={<Tabs />}
        profile={
          <CardContainer
            firstname={user.firstname}
            surname={user.surname}
            phonenumber={user.phonenumber}
            email={user.email}
          />
        }
      />
      {/* </main> */}
    </>
  );
}
