import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";
import Link from "next/link";


import {  NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

import Container from "../components/Container";
import ContentMain from "../components/ContentMain";

const inter = Inter({ subsets: ["latin"] });


export default function Home() {
  const [login, setLogin] = useState(false);
  

  return (
    <>
      <Head>
        <title>LetChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Container logo={true}>
          {!login ? (
            <ContentMain link={<Link href="/sign">Sign In</Link>}  description="The secure communication platform for landlords and tenants. Easily share and store important documents while keeping all communication organized in one place. Say goodbye to the hassle of back-and-forth emails and phone calls."/>
      
          ) : (
           //redirect to login page
           
            <h1>
              Redirect user to login page
            </h1>
                
            
          )}
        </Container>
      </main>
    </>
  );
}
