import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Ticket from "../components/Ticket";
import Container from "../components/Container";
const inter = Inter({ subsets: ["latin"] });

export default function JobBoard() {
  function openTicket(id: number) {
    console.log(id);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Ticket openTicket={openTicket} />
      </Container>
    </>
  );
}
