import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Ticket from "../components/Ticket";
const inter = Inter({ subsets: ["latin"] });

export default function JobBoard() {
  function openTicket(id: number) {
    console.log(id);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <h1 className="text-3xl font-bold underline text-light-primary">
          LetChat Job Board
        </h1>
        <Ticket openTicket={openTicket} />
      </main>
    </>
  );
}
