import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Container from "../components/Container";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <div className="hero pr-[65%]">
            <div className="hero-content flex-col lg:flex-row-reverse max-w-[28rem]">
              <div>
                <h1 className="text-5xl font-bold">LetChat</h1>
                <p className="py-6">
                  Provident cupiditate voluptatem et in. Quaerat fugiat ut
                  assumenda excepturi exercitationem quasi. In deleniti eaque
                  aut repudiandae et a id nisi.
                </p>
                <button className="btn btn-primary w-full text-transform: capitalize">
                  Sign Up
                </button>
              </div>
            </div>
          </div>
        </Container>
      </main>
    </>
  );
}
