import Head from "next/head";

import Container from "../components/Container";

const privacypolicy = () => {
  return (
    <>
      <Head>
        <title>LetChat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <div className=" m-auto max-w-3xl my-4">
          <h1>Privacy Policy</h1>

          <p>Last updated January 23, 2023</p>
          <br />
          <p>
            This privacy notice for Git Gud ('Company', 'we', 'us', or 'our'),
            describes how and why we might collect, store, use, and/or share
            ('process') your information when you use our services ('Services'),
            such as when you:
          </p>
          <p>
            Visit our website at http://www.letchat.co.uk, or any website of
            ours that links to this privacy notice
          </p>
          <p>
            Engage with us in other related ways, including any sales,
            marketing, or events
          </p>
          <p>
            Questions or concerns? Reading this privacy notice will help you
            understand your privacy rights and choices. If you do not agree with
            our policies and practices, please do not use our Services. If you
            still have any questions or concerns, please contact us at
            letchatgitgud@gmail.com.
          </p>
          <br />
          <p>SUMMARY OF KEY POINTS</p>
          <br />
          <p>
            This summary provides key points from our privacy notice, but you
            can find out more details about any of these topics by clicking the
            link following each key point or by using our table of contents
            below to find the section you are looking for. You can also click
            here to go directly to our table of contents.
          </p>
          <br />
          <p>
            What personal information do we process? When you visit, use, or
            navigate our Services, we may process personal information depending
            on how you interact with Git Gud and the Services, the choices you
            make, and the products and features you use. Click here to learn
            more.
          </p>
          <br />
          <p>
            Do we process any sensitive personal information? We do not process
            sensitive personal information.
          </p>
          <br />
          <p>
            Do we receive any information from third parties? We do not receive
            any information from third parties.
          </p>
          <br />
          <p>
            How do we process your information? We process your information to
            provide, improve, and administer our Services, communicate with you,
            for security and fraud prevention, and to comply with law. We may
            also process your information for other purposes with your consent.
            We process your information only when we have a valid legal reason
            to do so. Click here to learn more.
          </p>
          <br />
          <p>
            In what situations and with which types of parties do we share
            personal information? We may share information in specific
            situations and with specific categories of third parties. Click here
            to learn more.
          </p>
          <br />
          <p>
            How do we keep your information safe? We have organisational and
            technical processes and procedures in place to protect your personal
            information. However, no electronic transmission over the internet
            or information storage technology can be guaranteed to be 100%
            secure, so we cannot promise or guarantee that hackers,
            cybercriminals, or other unauthorised third parties will not be able
            to defeat our security and improperly collect, access, steal, or
            modify your information. Click here to learn more.
          </p>
          <br />
          <p>
            What are your rights? Depending on where you are located
            geographically, the applicable privacy law may mean you have certain
            rights regarding your personal information. Click here to learn
            more.
          </p>
          <br />
          <p>
            How do you exercise your rights? The easiest way to exercise your
            rights is by filling out our data subject request form available
            here: http://www.letchat.co.uk/data-request, or by contacting us. We
            will consider and act upon any request in accordance with applicable
            data protection laws.
          </p>
          <br />
          <p>
            Want to learn more about what Git Gud does with any information we
            collect? Click here to review the notice in full.
          </p>
          <br />
          <br />
          <p>TABLE OF CONTENTS</p>
          <br />
          <p>1. WHAT INFORMATION DO WE COLLECT?</p>
          <p>2. HOW DO WE PROCESS YOUR INFORMATION?</p>
          <p>
            3. WHAT LEGAL BASES DO WE RELY ON TO PROCESS YOUR PERSONAL
            INFORMATION?
          </p>
          <p>4. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</p>
          <p>5. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</p>
          <p>6. HOW DO WE HANDLE YOUR SOCIAL LOGINS?</p>
          <p>7. IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY?</p>
          <p>8. HOW LONG DO WE KEEP YOUR INFORMATION?</p>
          <p>9. HOW DO WE KEEP YOUR INFORMATION SAFE?</p>
          <p>10. DO WE COLLECT INFORMATION FROM MINORS?</p>
          <p>11. WHAT ARE YOUR PRIVACY RIGHTS?</p>
          <p>12. CONTROLS FOR DO-NOT-TRACK FEATURES</p>
          <p>13. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</p>
          <p>14. DO WE MAKE UPDATES TO THIS NOTICE?</p>
          <p>15. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</p>
          <p>
            16. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM
            YOU?
          </p>
          <br />
          <br />
          <p>1. WHAT INFORMATION DO WE COLLECT?</p>
          <br />
          <p>Personal information you disclose to us</p>
          <br />
          <p>
            In Short: We collect personal information that you provide to us.
          </p>
          <br />
          <p>
            We collect personal information that you voluntarily provide to us
            when you register on the Services, express an interest in obtaining
            information about us or our products and Services, when you
            participate in activities on the Services, or otherwise when you
            contact us.
          </p>
          <br />
          <p>
            Personal Information Provided by You. The personal information that
            we collect depends on the context of your interactions with us and
            the Services, the choices you make, and the products and features
            you use. The personal information we collect may include the
            following:
          </p>
          <p>names</p>
          <p>phone numbers</p>
          <p>email addresses</p>
          <p>passwords</p>
          <p>mailing addresses</p>
          <p>contact or authentication data</p>
          <p>Sensitive Information. We do not process sensitive information.</p>
          <br />
          <p>
            Social Media Login Data. We may provide you with the option to
            register with us using your existing social media account details,
            like your Facebook, Twitter, or other social media account. If you
            choose to register in this way, we will collect the information
            described in the section called 'HOW DO WE HANDLE YOUR SOCIAL
            LOGINS?' below.
          </p>
          <br />
          <p>
            All personal information that you provide to us must be true,
            complete, and accurate, and you must notify us of any changes to
            such personal information.
          </p>
          <br />
          <p>Information automatically collected</p>
          <br />
          <p>
            In Short: Some information - such as your Internet Protocol (IP)
            address and/or browser and device characteristics - is collected
            automatically when you visit our Services.
          </p>
          <br />
          <p>
            We automatically collect certain information when you visit, use, or
            navigate the Services. This information does not reveal your
            specific identity (like your name or contact information) but may
            include device and usage information, such as your IP address,
            browser and device characteristics, operating system, language
            preferences, referring URLs, device name, country, location,
            information about how and when you use our Services, and other
            technical information. This information is primarily needed to
            maintain the security and operation of our Services, and for our
            internal analytics and reporting purposes.
          </p>
          <br />
          <p>
            Like many businesses, we also collect information through cookies
            and similar technologies.
          </p>
          <br />
          <p>The information we collect includes:</p>
          <p>
            Log and Usage Data. Log and usage data is service-related,
            diagnostic, usage, and performance information our servers
            automatically collect when you access or use our Services and which
            we record in log files. Depending on how you interact with us, this
            log data may include your IP address, device information, browser
            type, and settings and information about your activity in the
            Services (such as the date/time stamps associated with your usage,
            pages and files viewed, searches, and other actions you take such as
            which features you use), device event information (such as system
            activity, error reports (sometimes called 'crash dumps'), and
            hardware settings).
          </p>
          <p>
            Device Data. We collect device data such as information about your
            computer, phone, tablet, or other device you use to access the
            Services. Depending on the device used, this device data may include
            information such as your IP address (or proxy server), device and
            application identification numbers, location, browser type, hardware
            model, Internet service provider and/or mobile carrier, operating
            system, and system configuration information.
          </p>
          <p>
            Location Data. We collect location data such as information about
            your device's location, which can be either precise or imprecise.
            How much information we collect depends on the type and settings of
            the device you use to access the Services. For example, we may use
            GPS and other technologies to collect geolocation data that tells us
            your current location (based on your IP address). You can opt out of
            allowing us to collect this information either by refusing access to
            the information or by disabling your Location setting on your
            device. However, if you choose to opt out, you may not be able to
            use certain aspects of the Services.
          </p>
          <p>2. HOW DO WE PROCESS YOUR INFORMATION?</p>
          <br />
          <p>
            In Short: We process your information to provide, improve, and
            administer our Services, communicate with you, for security and
            fraud prevention, and to comply with law. We may also process your
            information for other purposes with your consent.
          </p>
          <br />
          <p>
            We process your personal information for a variety of reasons,
            depending on how you interact with our Services, including:
          </p>
          <p>
            To facilitate account creation and authentication and otherwise
            manage user accounts. We may process your information so you can
            create and log in to your account, as well as keep your account in
            working order.
          </p>
          <p>
            To deliver and facilitate delivery of services to the user. We may
            process your information to provide you with the requested service.
          </p>
          <p>
            To respond to user inquiries/offer support to users. We may process
            your information to respond to your inquiries and solve any
            potential issues you might have with the requested service.
          </p>
          <p>
            To send administrative information to you. We may process your
            information to send you details about our products and services,
            changes to our terms and policies, and other similar information.
          </p>
          <p>
            To fulfil and manage your orders. We may process your information to
            fulfil and manage your orders, payments, returns, and exchanges made
            through the Services.
          </p>
          <br />
          <br />
          <p>
            To enable user-to-user communications. We may process your
            information if you choose to use any of our offerings that allow for
            communication with another user.
          </p>
          <br />
          <br />
          <p>
            To request feedback. We may process your information when necessary
            to request feedback and to contact you about your use of our
            Services.
          </p>
          <p>
            To send you marketing and promotional communications. We may process
            the personal information you send to us for our marketing purposes,
            if this is in accordance with your marketing preferences. You can
            opt out of our marketing emails at any time. For more information,
            see 'WHAT ARE YOUR PRIVACY RIGHTS?' below).
          </p>
          <p>
            To protect our Services. We may process your information as part of
            our efforts to keep our Services safe and secure, including fraud
            monitoring and prevention.
          </p>
          <p>
            To identify usage trends. We may process information about how you
            use our Services to better understand how they are being used so we
            can improve them.
          </p>
          <p>
            To determine the effectiveness of our marketing and promotional
            campaigns. We may process your information to better understand how
            to provide marketing and promotional campaigns that are most
            relevant to you.
          </p>
          <p>
            To save or protect an individual's vital interest. We may process
            your information when necessary to save or protect an individual's
            vital interest, such as to prevent harm.
          </p>
          <br />
          <p>3. WHAT LEGAL BASES DO WE RELY ON TO PROCESS YOUR INFORMATION?</p>
          <br />
          <p>
            In Short: We only process your personal information when we believe
            it is necessary and we have a valid legal reason (i.e. legal basis)
            to do so under applicable law, like with your consent, to comply
            with laws, to provide you with services to enter into or fulfil our
            contractual obligations, to protect your rights, or to fulfil our
            legitimate business interests.
          </p>
          <br />
          <p>
            The General Data Protection Regulation (GDPR) and UK GDPR require us
            to explain the valid legal bases we rely on in order to process your
            personal information. As such, we may rely on the following legal
            bases to process your personal information:
          </p>
          <p>
            Consent. We may process your information if you have given us
            permission (i.e. consent) to use your personal information for a
            specific purpose. You can withdraw your consent at any time. Click
            here to learn more.
          </p>
          <p>
            Performance of a Contract. We may process your personal information
            when we believe it is necessary to fulfil our contractual
            obligations to you, including providing our Services or at your
            request prior to entering into a contract with you.
          </p>
          <p>
            Legitimate Interests. We may process your information when we
            believe it is reasonably necessary to achieve our legitimate
            business interests and those interests do not outweigh your
            interests and fundamental rights and freedoms. For example, we may
            process your personal information for some of the purposes described
            in order to:
          </p>
          <p>
            Send users information about special offers and discounts on our
            products and services
          </p>
          <p>
            Analyse how our Services are used so we can improve them to engage
            and retain users
          </p>
          <p>Support our marketing activities</p>
          <p>Diagnose problems and/or prevent fraudulent activities</p>
          <p>
            Understand how our users use our products and services so we can
            improve user experience
          </p>
          <p>
            Legal Obligations. We may process your information where we believe
            it is necessary for compliance with our legal obligations, such as
            to cooperate with a law enforcement body or regulatory agency,
            exercise or defend our legal rights, or disclose your information as
            evidence in litigation in which we are involved.
          </p>
          <p>
            Vital Interests. We may process your information where we believe it
            is necessary to protect your vital interests or the vital interests
            of a third party, such as situations involving potential threats to
            the safety of any person.
          </p>
          <br />
          <p>4. WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</p>
          <br />
          <p>
            In Short: We may share information in specific situations described
            in this section and/or with the following categories of third
            parties.
          </p>
          <br />
          <p>
            Vendors, Consultants, and Other Third-Party Service Providers. We
            may share your data with third-party vendors, service providers,
            contractors, or agents ('third parties') who perform services for us
            or on our behalf and require access to such information to do that
            work. We have contracts in place with our third parties, which are
            designed to help safeguard your personal information. This means
            that they cannot do anything with your personal information unless
            we have instructed them to do it. They will also not share your
            personal information with any organisation apart from us. They also
            commit to protect the data they hold on our behalf and to retain it
            for the period we instruct. The categories of third parties we may
            share personal information with are as follows:
          </p>
          <p>Data Analytics Services</p>
          <br />
          <p>
            We also may need to share your personal information in the following
            situations:
          </p>
          <p>
            Business Transfers. We may share or transfer your information in
            connection with, or during negotiations of, any merger, sale of
            company assets, financing, or acquisition of all or a portion of our
            business to another company.
          </p>
          <p>
            Other Users. When you share personal information (for example, by
            posting comments, contributions, or other content to the Services)
            or otherwise interact with public areas of the Services, such
            personal information may be viewed by all users and may be publicly
            made available outside the Services in perpetuity. If you interact
            with other users of our Services and register for our Services
            through a social network (such as Facebook), your contacts on the
            social network will see your name, profile photo, and descriptions
            of your activity. Similarly, other users will be able to view
            descriptions of your activity, communicate with you within our
            Services, and view your profile.
          </p>
          <br />
          <p>5. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</p>
          <br />
          <p>
            In Short: We may use cookies and other tracking technologies to
            collect and store your information.
          </p>
          <br />
          <p>
            We may use cookies and similar tracking technologies (like web
            beacons and pixels) to access or store information. Specific
            information about how we use such technologies and how you can
            refuse certain cookies is set out in our Cookie Notice.
          </p>
          <br />
          <p>6. HOW DO WE HANDLE YOUR SOCIAL LOGINS?</p>
          <br />
          <p>
            In Short: If you choose to register or log in to our Services using
            a social media account, we may have access to certain information
            about you.
          </p>
          <br />
          <p>
            Our Services offer you the ability to register and log in using your
            third-party social media account details (like your Facebook or
            Twitter logins). Where you choose to do this, we will receive
            certain profile information about you from your social media
            provider. The profile information we receive may vary depending on
            the social media provider concerned, but will often include your
            name, email address, friends list, and profile picture, as well as
            other information you choose to make public on such a social media
            platform.
          </p>
          <br />
          <p>
            We will use the information we receive only for the purposes that
            are described in this privacy notice or that are otherwise made
            clear to you on the relevant Services. Please note that we do not
            control, and are not responsible for, other uses of your personal
            information by your third-party social media provider. We recommend
            that you review their privacy notice to understand how they collect,
            use, and share your personal information, and how you can set your
            privacy preferences on their sites and apps.
          </p>
          <br />
          <p>7. IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY?</p>
          <br />
          <p>
            In Short: We may transfer, store, and process your information in
            countries other than your own.
          </p>
          <br />
          <p>
            Our servers are located in the United States, and Ireland. If you
            are accessing our Services from outside the United States, and
            Ireland, please be aware that your information may be transferred
            to, stored, and processed by us in our facilities and by those third
            parties with whom we may share your personal information (see 'WHEN
            AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?' above), in the
            United States, and other countries.
          </p>
          <br />
          <p>
            If you are a resident in the European Economic Area (EEA) or United
            Kingdom (UK), then these countries may not necessarily have data
            protection laws or other similar laws as comprehensive as those in
            your country. However, we will take all necessary measures to
            protect your personal information in accordance with this privacy
            notice and applicable law.
          </p>
          <br />
          <p>European Commission's Standard Contractual Clauses:</p>
          <br />
          <p>
            We have implemented measures to protect your personal information,
            including by using the European Commission's Standard Contractual
            Clauses for transfers of personal information between our group
            companies and between us and our third-party providers. These
            clauses require all recipients to protect all personal information
            that they process originating from the EEA or UK in accordance with
            European data protection laws and regulations. Our Standard
            Contractual Clauses can be provided upon request. We have
            implemented similar appropriate safeguards with our third-party
            service providers and partners and further details can be provided
            upon request.
          </p>
          <br />
          <p>8. HOW LONG DO WE KEEP YOUR INFORMATION?</p>
          <br />
          <p>
            In Short: We keep your information for as long as necessary to
            fulfil the purposes outlined in this privacy notice unless otherwise
            required by law.
          </p>
          <br />
          <p>
            We will only keep your personal information for as long as it is
            necessary for the purposes set out in this privacy notice, unless a
            longer retention period is required or permitted by law (such as
            tax, accounting, or other legal requirements). No purpose in this
            notice will require us keeping your personal information for longer
            than three (3) months past the termination of the user's account.
          </p>
          <br />
          <p>
            When we have no ongoing legitimate business need to process your
            personal information, we will either delete or anonymise such
            information, or, if this is not possible (for example, because your
            personal information has been stored in backup archives), then we
            will securely store your personal information and isolate it from
            any further processing until deletion is possible.
          </p>
          <br />
          <p>9. HOW DO WE KEEP YOUR INFORMATION SAFE?</p>
          <br />
          <p>
            In Short: We aim to protect your personal information through a
            system of organisational and technical security measures.
          </p>
          <br />
          <p>
            We have implemented appropriate and reasonable technical and
            organisational security measures designed to protect the security of
            any personal information we process. However, despite our safeguards
            and efforts to secure your information, no electronic transmission
            over the Internet or information storage technology can be
            guaranteed to be 100% secure, so we cannot promise or guarantee that
            hackers, cybercriminals, or other unauthorised third parties will
            not be able to defeat our security and improperly collect, access,
            steal, or modify your information. Although we will do our best to
            protect your personal information, transmission of personal
            information to and from our Services is at your own risk. You should
            only access the Services within a secure environment.
          </p>
          <br />
          <p>10. DO WE COLLECT INFORMATION FROM MINORS?</p>
          <br />
          <p>
            In Short: We do not knowingly collect data from or market to
            children under 18 years of age.
          </p>
          <br />
          <p>
            We do not knowingly solicit data from or market to children under 18
            years of age. By using the Services, you represent that you are at
            least 18 or that you are the parent or guardian of such a minor and
            consent to such minor dependent's use of the Services. If we learn
            that personal information from users less than 18 years of age has
            been collected, we will deactivate the account and take reasonable
            measures to promptly delete such data from our records. If you
            become aware of any data we may have collected from children under
            age 18, please contact us at letchatgitgud@gmail.com.
          </p>
          <br />
          <p>11. WHAT ARE YOUR PRIVACY RIGHTS?</p>
          <br />
          <p>
            In Short: In some regions, such as the European Economic Area (EEA)
            and United Kingdom (UK), you have rights that allow you greater
            access to and control over your personal information. You may
            review, change, or terminate your account at any time.
          </p>
          <br />
          <p>
            In some regions (like the EEA and UK), you have certain rights under
            applicable data protection laws. These may include the right (i) to
            request access and obtain a copy of your personal information, (ii)
            to request rectification or erasure; (iii) to restrict the
            processing of your personal information; and (iv) if applicable, to
            data portability. In certain circumstances, you may also have the
            right to object to the processing of your personal information. You
            can make such a request by contacting us by using the contact
            details provided in the section 'HOW CAN YOU CONTACT US ABOUT THIS
            NOTICE?' below.
          </p>
          <br />
          <p>
            We will consider and act upon any request in accordance with
            applicable data protection laws.
          </p>
          <p>
            If you are located in the EEA or UK and you believe we are
            unlawfully processing your personal information, you also have the
            right to complain to your local data protection supervisory
            authority. You can find their contact details here:
            https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm.
          </p>
          <br />
          <p>
            If you are located in Switzerland, the contact details for the data
            protection authorities are available here:
            https://www.edoeb.admin.ch/edoeb/en/home.html.
          </p>
          <br />
          <p>
            Withdrawing your consent: If we are relying on your consent to
            process your personal information, you have the right to withdraw
            your consent at any time. You can withdraw your consent at any time
            by contacting us by using the contact details provided in the
            section 'HOW CAN YOU CONTACT US ABOUT THIS NOTICE?' below.
          </p>
          <br />
          <p>
            However, please note that this will not affect the lawfulness of the
            processing before its withdrawal nor, will it affect the processing
            of your personal information conducted in reliance on lawful
            processing grounds other than consent.
          </p>
          <br />
          <p>
            Opting out of marketing and promotional communications: You can
            unsubscribe from our marketing and promotional communications at any
            time by clicking on the unsubscribe link in the emails that we send,
            or by contacting us using the details provided in the section 'HOW
            CAN YOU CONTACT US ABOUT THIS NOTICE?' below. You will then be
            removed from the marketing lists. However, we may still communicate
            with you - for example, to send you service-related messages that
            are necessary for the administration and use of your account, to
            respond to service requests, or for other non-marketing purposes.
          </p>
          <br />
          <p>Account Information</p>
          <br />
          <p>
            If you would at any time like to review or change the information in
            your account or terminate your account, you can:
          </p>
          <p>Log in to your account settings and update your user account.</p>
          <p>
            Upon your request to terminate your account, we will deactivate or
            delete your account and information from our active databases.
            However, we may retain some information in our files to prevent
            fraud, troubleshoot problems, assist with any investigations,
            enforce our legal terms and/or comply with applicable legal
            requirements.
          </p>
          <br />
          <p>
            Cookies and similar technologies: Most Web browsers are set to
            accept cookies by default. If you prefer, you can usually choose to
            set your browser to remove cookies and to reject cookies. If you
            choose to remove cookies or reject cookies, this could affect
            certain features or services of our Services. To opt out of
            interest-based advertising by advertisers on our Services visit
            http://www.aboutads.info/choices/.
          </p>
          <br />
          <p>
            If you have questions or comments about your privacy rights, you may
            email us at letchatgitgud@gmail.com.
          </p>
          <br />
          <p>12. CONTROLS FOR DO-NOT-TRACK FEATURES</p>
          <br />
          <p>
            Most web browsers and some mobile operating systems and mobile
            applications include a Do-Not-Track ('DNT') feature or setting you
            can activate to signal your privacy preference not to have data
            about your online browsing activities monitored and collected. At
            this stage no uniform technology standard for recognising and
            implementing DNT signals has been finalised. As such, we do not
            currently respond to DNT browser signals or any other mechanism that
            automatically communicates your choice not to be tracked online. If
            a standard for online tracking is adopted that we must follow in the
            future, we will inform you about that practice in a revised version
            of this privacy notice.
          </p>
          <br />
          <p>13. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</p>
          <br />
          <p>
            In Short: Yes, if you are a resident of California, you are granted
            specific rights regarding access to your personal information.
          </p>
          <br />
          <p>
            California Civil Code Section 1798.83, also known as the 'Shine The
            Light' law, permits our users who are California residents to
            request and obtain from us, once a year and free of charge,
            information about categories of personal information (if any) we
            disclosed to third parties for direct marketing purposes and the
            names and addresses of all third parties with which we shared
            personal information in the immediately preceding calendar year. If
            you are a California resident and would like to make such a request,
            please submit your request in writing to us using the contact
            information provided below.
          </p>
          <br />
          <p>
            If you are under 18 years of age, reside in California, and have a
            registered account with Services, you have the right to request
            removal of unwanted data that you publicly post on the Services. To
            request removal of such data, please contact us using the contact
            information provided below and include the email address associated
            with your account and a statement that you reside in California. We
            will make sure the data is not publicly displayed on the Services,
            but please be aware that the data may not be completely or
            comprehensively removed from all our systems (e.g. backups, etc.).
          </p>
          <br />
          <p>14. DO WE MAKE UPDATES TO THIS NOTICE?</p>
          <br />
          <p>
            In Short: Yes, we will update this notice as necessary to stay
            compliant with relevant laws.
          </p>
          <br />
          <p>
            We may update this privacy notice from time to time. The updated
            version will be indicated by an updated 'Revised' date and the
            updated version will be effective as soon as it is accessible. If we
            make material changes to this privacy notice, we may notify you
            either by prominently posting a notice of such changes or by
            directly sending you a notification. We encourage you to review this
            privacy notice frequently to be informed of how we are protecting
            your information.
          </p>
          <br />
          <p>15. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</p>
          <br />
          <p>
            If you have questions or comments about this notice, you may email
            us at gitgudletchat@gmail.com or by post to:
          </p>
          <br />
          <p>Git Gud</p>
          <p>123 Postgres Way</p>
          <p>Norwich NR12 34B</p>
          <p>United Kingdom</p>
          <br />
          <p>
            16. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM
            YOU?
          </p>
          <br />
          <p>
            Based on the applicable laws of your country, you may have the right
            to request access to the personal information we collect from you,
            change that information, or delete it. To request to review, update,
            or delete your personal information, please visit:
            http://www.letchat.co.uk/data-request.
          </p>
        </div>
      </Container>
    </>
  );
};

export default privacypolicy;
